### ISSUE TITLE
Restarting (AT+RST)

### ISSUE THREAD

**Issue by dbrgn** [pegasus-aero/rt-esp-at-nal#5]
I experimented with a command to restart the module with AT+RST. However, this isn't really a "regular" command, because after the "OK" and the restart, the module outputs some binary garbage content first. We'd need to somehow flush the input buffers before carrying on. Maybe an "AT" command should be sent, to verify that the module is in a known state.

Here's my not-yet-so-reliable attempt:

```diff
diff --git a/examples/linux.rs b/examples/linux.rs
index e1aaa17..f256e6f 100644
--- a/examples/linux.rs
+++ b/examples/linux.rs
@@ -113,6 +113,9 @@ fn main() {
 
     // ESP AT adapter
     let mut adapter: Adapter<_, _, TIMER_HZ, ESP_TX_SIZE, ESP_RX_SIZE> = Adapter::new(client, esp_timer);
+    thread::sleep_ms(1000);
+    adapter.restart().unwrap();
+    thread::sleep_ms(1000);
 
     // Join WIFI access point
     println!("Join WiFi \"{}\"...", ssid);
diff --git a/src/commands.rs b/src/commands.rs
index b9e536d..fb86f30 100644
--- a/src/commands.rs
+++ b/src/commands.rs
@@ -19,6 +19,37 @@ pub trait CommandErrorHandler {
     fn command_error(&self, error: AtError) -> Self::Error;
 }
 
+/// Generic error enum
+#[derive(Clone, Debug, PartialEq)]
+pub enum GenericError {
+    /// Generic error
+    Error(AtError),
+
+    /// Received an unexpected WouldBlock. The most common cause of errors is an incorrect mode of the client.
+    /// This must be either timeout or blocking.
+    UnexpectedWouldBlock,
+}
+
+/// Restarts the module
+#[derive(Clone, Default, AtatCmd)]
+#[at_cmd("+RST", NoResponse, timeout_ms = 1_000)]
+pub struct RestartCommand {}
+
+impl RestartCommand {
+    pub fn new() -> Self {
+        Self {}
+    }
+}
+
+impl CommandErrorHandler for RestartCommand {
+    type Error = GenericError;
+    const WOULD_BLOCK_ERROR: Self::Error = GenericError::UnexpectedWouldBlock;
+
+    fn command_error(&self, error: AtError) -> Self::Error {
+        GenericError::Error(error)
+    }
+}
+
 /// Sets the WIFI mode + optionally enables/disables auto_connect
 #[derive(Clone, Default, AtatCmd)]
 #[at_cmd("+CWMODE", NoResponse, timeout_ms = 1_000)]
diff --git a/src/wifi.rs b/src/wifi.rs
index 838bcc4..a0af655 100644
--- a/src/wifi.rs
+++ b/src/wifi.rs
@@ -29,8 +29,8 @@
 //! assert_eq!("10.0.0.181", address.ipv4.unwrap().to_string());
 //! ````
 use crate::commands::{
-    AccessPointConnectCommand, CommandErrorHandler, ObtainLocalAddressCommand, SetSocketReceivingModeCommand,
-    WifiModeCommand,
+    AccessPointConnectCommand, CommandErrorHandler, GenericError, ObtainLocalAddressCommand, RestartCommand,
+    SetSocketReceivingModeCommand, WifiModeCommand,
 };
 use crate::responses::LocalAddressResponse;
 use crate::stack::SocketState;
@@ -219,6 +219,22 @@ impl<A: AtatClient, T: Timer<TIMER_HZ>, const TIMER_HZ: u32, const TX_SIZE: usiz
         }
     }
 
+    /// Creates a new network adapter and immediately restarts the module.
+    /// Client needs to be in timeout or blocking mode
+    pub fn restarted(client: A, timer: T) -> Result<Self, GenericError> {
+        let mut client = Self::new(client, timer);
+        client.restart()?;
+        Ok(client)
+    }
+
+    /// Restarts the module
+    pub fn restart(&mut self) -> Result<(), GenericError> {
+        let command = RestartCommand::new();
+        self.send_command(command)?;
+        self.client.reset();
+        Ok(())
+    }
+
     /// Processes all pending messages in the queue
     pub(crate) fn process_urc_messages(&mut self) {
         while let Some(message) = self.client.check_urc::<URCMessages<RX_SIZE>>() {
```

Do you have experience with this? (My goal would be to start from a known, reliable state every time.)

**Comment by marius-meissner** [comment]
>  outputs some binary garbage content first.

As far as I know, the module sends at first some version information but at a different UART speed. Just a side note :)

Anyway, restarting seems like a good feature to implement. The module sends a ready message, when the restart is done.
In fact, this message is already parsed, but not handled yet:
https://github.com/pegasus-aero/rt-esp-at-nal/blob/84751bf16f758c882ac04ed0c761754792bf2f4e/src/urc.rs#L13

So, we can issue the restart and wait then for the ready message. Normally, the current URC parser implementation ignores/skips the binary garbage at the beginning.

I will implement a first draft soon.

**Comment by dbrgn** [comment]
Oh, that makes sense. Yeah, handling `Ready` probably is the way to go.

**Comment by marius-meissner** [comment]
A first draft has been implemented in restart branch (s. #9). At least in our project or rather on our hardware (custom PCB with RP2040) had worked.
Please feel free to test on your side and add feedback to the code changes. 

> Normally, the current URC parser implementation ignores/skips the binary garbage at the beginning.
However, I was wrong about that, so I added another (sub)parser for Boot message. 

I had already considered whether we should discard unknown URC messages in general. But this would cause problems, as the URC parser has a higher priority than the response parser at ATATA.

**Comment by marius-meissner** [comment]
Closing, as #9 has been merged and will be released soon.
For any tests results or further proposals, new issues will be created.
