### ISSUE TITLE
AT+CWAUTOCONN

### ISSUE THREAD

**Issue by dbrgn** [pegasus-aero/rt-esp-at-nal#6]
The [AT+CWAUTOCONN](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/Wi-Fi_AT_Commands.html#wifi-at) command controls whether the module automatically joins a previously joined network on power-on. This can cause timing-sensitive issues when sending other commands. For example, sending AT+CIPMUX=1 fails with an error in some connection states.

I'm not sure what the best way to handle this would be. For reliability, it's probably best to disable autoconnection, to avoid race conditions. For faster connections, it can be left enabled. However, I don't know whether esp-at-nal was written with the possibility in mind that the WiFi can connect at any point in time, even when not having issued a join command?

For now, I configured the module manually via serial console to not do any auto-connecting (the change is permanent). This could be an option or method in esp-rt-nal though. Potentially it could even be part of the initial setup logic.

Do you have any thoughts on this?

**Comment by dbrgn** [comment]
> You could try to enable autoconect and test then the connection state after a restart using [get_join_state()](https://docs.rs/esp-at-nal/0.1.1/esp_at_nal/wifi/struct.Adapter.html#method.get_join_status).

I [do that already](https://github.com/coredump-ch/nixie-counter/blob/d49c832c3372242677a22d43e36bc5feca4ab7d4/firmware/src/main.rs#L466), but it's still asynchronous and thus prone to race conditions. Or is there a way to "block until potential joining of a pre-joined wifi network is done"? I'm not aware of any such command, so for now I always connect on start (with autoconnect disabled), and then (to prevent the `AT+CIPMUX=1` command that is emitted when opening a socket) only open a socket once the device is connected.

**Comment by dbrgn** [comment]
My original idea was to open the socket immediately, right after creating the adapter. From the way it is implemented, it _should_ work (after all, a socket is just an integer where esp-at-hal ensures that it's not accidentally re-used). With RTIC, this makes it simpler because you can make the socket a shared resource which is re-used by future connections.

However, if the socket needs to wait for the wifi joining, which happens in a task, I cannot instantiate the socket in `init` and must do a delayed initialization of the socket at runtime. Not a big deal, but that's how I stumbled over the issue that the socket initialization (where `AT+CIPMUX=1` is sent) fails in some connection states.

**Comment by marius-meissner** [comment]
Ok, got it. In fact, we are using RTIC already internally and yes, sockets are currently created within a task :)
So, I fully understand and support your intention. 

What about moving `AT+CIPMUX=1` from [socket()](https://docs.rs/esp-at-nal/0.1.2/esp_at_nal/wifi/struct.Adapter.html#method.socket) to [connect()](https://docs.rs/esp-at-nal/0.1.2/esp_at_nal/wifi/struct.Adapter.html#method.connect) method?

**Comment by marius-meissner** [comment]
Closing, as #8 has been merged. For any relevant open discussion points, like "moving AT+CIPMUX=1 from [socket()](https://docs.rs/esp-at-nal/0.1.2/esp_at_nal/wifi/struct.Adapter.html#method.socket) to [connect()](https://docs.rs/esp-at-nal/0.1.2/esp_at_nal/wifi/struct.Adapter.html#method.connect) method" I would suggest to open a new issue.

**Comment by dbrgn** [comment]
A bit late, but: Thanks 😄
